name: Android CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        required: true

      build_android:
        type: boolean
        default: true
        description: Android
      build_ios:
        type: boolean
        default: true
        description: iOS

run-name: "Release #${{ github.run_number }} ${{ (inputs.build_android == true) && '#android' }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
