name: 
on:
  workflow_dispatch:
    inputs:
      environments:
        type: choice
        description: Make a choice
        options:
        - dev1
        - staging & prod
        
jobs:
  build:
    name: GitHub Actions Test Vars
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev1
          - staging
          - prod
        platform: [android, ios]

    if: (inputs.environments == 'dev1' && matrix.environment == dev1) || (inputs.environments == 'staging & prod' && (matrix.environment == 'staging' || matrix.environment == 'prod'))
    environment: ${{ matrix.environment }}
    
    steps:
      - name: Test
        run: echo "test"
