name: matrix
on:
  workflow_dispatch:
    inputs:
      environments:
        type: choice
        description: Make a choice
        options:
        - dev1
        - staging & prod
        
jobs:
  build:
    name: GitHub Actions Test Vars
    runs-on: ubuntu-latest

    env:
      envs: "['dev1','staging']"

    strategy:
      matrix:
        environment: ${{ fromJSON(env.envs) }}
        platform: [android, ios]

    environment: ${{ matrix.environment }}
    
    steps:
      - name: Test
        run: echo "test"
