name: Parent w

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the new version of the release. Eg: 4.22.0"
        required: true

permissions:
  contents: write
  id-token: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase (${{ github.ref_name }})
        uses: actions/checkout@v3
        
      - name: Output build information 001
        run: |
          echo "test abcd"

      - name: Download Paragon driver from Paragon website
        run: wget "https://dl.paragon-software.com/APC/WD/NTFS4Mac/15.10.592/NTFS-15.10.592.dmg" -P paragon-driver
      
      - name: Zip the downloaded file
        working-directory: paragon-driver
        run: zip "NTFS-15.10.592" ./*
        
      # - name: reuse
      #   uses: ./.github/workflows/child-workflow.yml
      #   with:
      #     environment: ${{ inputs.environment }}
      #     branch: ${{ inputs.branch }}
      #     build-number: ${{ github.run_number }}

      - name: upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: paragon_driver
          path: paragon-driver/*

      - name: Output build information 88
        run: |
          echo "test efg"
