name: GitHub Actions Test Promotion
run-name: GitHub Actions Test Vars ${{ github.run_number }} - ${{ github.event.inputs.environment }}
on:

  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        default: dev1
        required: true
        
jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    environment: dev
      
    steps:
      - name: test one
        run: echo "job 1"
        
  job_two:
    name: Job Two
    runs-on: ubuntu-latest
    environment: prod
    needs: job_one
      
    steps:
      - name: test one
        run: echo "job 2"
