name: Disc - Release Build & Generate Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the new version of the release. Eg: 4.4.0"
        default: 4.4.0
        required: true
      generateProd:
        type: boolean
        default: false
        description: Generate PROD build

run-name: "WD Discovery - Release Build & Generate Artifacts qa1 ${{ inputs.generateProd && '& prod' || '' }} #${{ github.run_number }}"

jobs:
  build:
    name: Build and generate artifacts
    runs-on: ubuntu-latest

    steps:
      - name: init workflow_dispatch
        run: echo "init workflow_dispatch to show `Run workflow` button in GitHub Actions UI"
