name: Add summary
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        default: dev1
        required: true
jobs:
  build:
    name: Add summary
    runs-on: macos-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Add summary
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
