name: Add summary
run-name: tttt
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        default: dev1
        required: true
jobs:
  build:
    name: Add summary
    runs-on: macos-latest

    steps:
      - run: echo "asdasd" >> $GITHUB_WORKFLOW
#       - name: Checkout codebase
#         uses: actions/checkout@v3
        
#       - name: Upload
#         uses: actions/upload-artifact@v3.1.2
#         with:
#           name: asc_file
#           path: android/app/build/outputs/apk/release/app-release.apk

#       - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
#       - run: echo 300 >> $GITHUB_RUN_NUMBER
