name: Add summary
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        default: dev1
        required: true
jobs:
  build:
    name: Add summary
    runs-on: macos-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: asc_file
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Add summary
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
