name: inputs.uploadToAWS
run-name: Upload staging config to S3 ${{ github.run_number }}

on: 
  workflow_dispatch:
    inputs:
      generateQA1:
        type: boolean
        default: false
        description: Generate QA1 build
      generatePROD:
        type: boolean
        default: false
        description: Generate PROD build
      uploadToAWS:
        type: boolean
        default: false
        description: Upload non-dev artifacts to S3

jobs:
  build:
    name: Dummy workflow dispatch
    runs-on: windows-latest

    steps:
      # - name: Checkout codebase
      #   uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: tree
        shell: bash
        run: |
          sudo apt-get install tree
          $path = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\"
          cd $path
          tree
          
      
      - name: List files
        run: |
          $path = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft"
          Get-ChildItem -Path $path
        
      # - run: |
      #     ls C:/Program Files/Microsoft Visual Studio/2022/Enterprise
      #   shell: bash
      
      - name: Install Node JS v10.15.3
        uses: actions/setup-node@v3
        with:
          node-version: 10.15.3

      - name: run VCTargetsPath
        run: |
          echo $env:VCTargetsPath
          echo $env:Path
      
      - name: echo $env:APPDATA
        run: |
          echo $env:APPDATA
          ls $env:APPDATA

      - name: Test print
        if: inputs.uploadToAWS == true && (inputs.generateQA1 == true || inputs.generatePROD == true)
        run: echo "test if"

      - name: Print artifacts S3 URLs
        env:
          ARTIFACT_S3_URL: https://s3.us-jj.com
        shell: bash
        run: |
          while IFS= read -r file; do
            filename=$(basename "$file")
            echo "${{ env.ARTIFACT_S3_URL }}$filename"
          done < <(find . -type f \( -name "WD-*" ! -name "WD-*-dev1-*" \))
        
