name: GitHub Actions Test Vars
run-name: GitHub Actions Test Vars
on:
  workflow_dispatch:
    inputs:
      version:
        description: "release_version"
        required: true
        default: "1"
jobs:
  build:
    name: GitHub Actions Test Vars
    runs-on: ubuntu-latest
    steps:
      - name: Test vars
        env:
          TEST_GITHUB_SECRET_VAL: ${{ secrets.TEST_GITHUB_SECRET }}
          TEST_GITHUB_VARIABLE_VAL: ${{ vars.TEST_GITHUB_VARIABLE }}
        run: chmod +x ./test_script.sh && ./test_script.sh
