name: inputs.uploadToAWS
run-name: Upload staging config to S3 ${{ github.run_number }}

on: 
  workflow_dispatch:
    inputs:
      generateQA1:
        type: boolean
        default: false
        description: Generate QA1 build
      generatePROD:
        type: boolean
        default: false
        description: Generate PROD build
      uploadToAWS:
        type: boolean
        default: false
        description: Upload non-dev artifacts to S3

jobs:
  build:
    name: Dummy workflow dispatch
    runs-on: macos-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Test print
        if: inputs.uploadToAWS == true && (inputs.generateQA1 == true || inputs.generatePROD == true)
        run: echo "test if"

      - name: Print artifacts S3 URLs
        env:
          ARTIFACT_S3_URL: https://s3.us-jj.com
        run: |
          while IFS= read -r file; do
            filename=$(basename "$file")
            echo "${{ env.ARTIFACT_S3_URL }}$filename"
          done < <(find . -type f \( -name "WD-*" ! -name "WD-*-dev1-*" \))
        
