name: GitHub Actions Test Vars
run-name: GitHub Actions Test Vars ${{ github.run_number }} - ${{ github.event.inputs.environment }}
on:
#   pull_request:
#     branches:
#       main
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        default: dev1
        required: true
        
jobs:
  build:
    name: GitHub Actions Test Vars
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    env:
      TEST_ENV_VAR: abc
      
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: echo test
        run: echo "${{ secrets.test_test_ }}" && echo "${{ vars.test_test_ }}" && echo "testt"
        
      - name: Print GitHub environment vars
        run: echo "${{ vars.TEST_ENV_VAR }}"
      
      - name: Print GitHub environment secrets
        run: echo "${{ secrets.TEST_ENV_SECRET }}"
      
      - name: Print
        run: echo "${{ env.TEST_ENV_VAR }}"

      - run: fail abc
      
      - name: Test accessing vars from other files
        env:
          TEST_GITHUB_SECRET_VAL: ${{ secrets.TEST_GITHUB_SECRET }}
          TEST_GITHUB_VARIABLE_VAL: ${{ vars.TEST_GITHUB_VARIABLE }}
        run: chmod +x scripts/test_script.sh && scripts/test_script.sh

      - name: test always
        if: failure()
        run: echo "done"
