name: GitHub Actions Test Vars
run-name: GitHub Actions Test Vars ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "release_version"
        required: true
        default: "1"
jobs:
  build:
    name: GitHub Actions Test Vars
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Test vars
        env:
          TEST_GITHUB_SECRET_VAL: ${{ secrets.TEST_GITHUB_SECRET }}
          TEST_GITHUB_VARIABLE_VAL: ${{ vars.TEST_GITHUB_VARIABLE }}
        run: chmod +x scripts/test_script.sh && scripts/test_script.sh
        
      - name: keystore
        run: echo "${{ secrets.KEYSTONE_ASC }}" > keystore-b64.txt
        
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: keystore-b64
          path: keystore-b64.txt
