name: Release sum
run-name: tttt
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        default: dev1
        required: true
jobs:
  summary:
    name: Build #summary
    runs-on: macos-latest
    
    env: 
      NEW_RUN_NAME: "new run name"

    steps:
#       - name: Get Workflow Run Details
#         id: workflow_run
#         run: |
#           echo "::set-output name=run_number::${{ github.event.workflow_run.id }}"
#           echo "::set-output name=run_name::${{ github.event.workflow_run.name }}"

#       - name: Rename Workflow Run
#         run: |
#           TOKEN="${{ secrets.GITHUB_TOKEN }}"
#           RUN_ID="${{ steps.workflow_run.outputs.run_number }}"
#           RUN_NAME="${{ steps.workflow_run.outputs.run_name }}"
#           NEW_RUN_NAME="New Run Name"

#           API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_ID}"
#           AUTH_HEADER="Authorization: Bearer $TOKEN"

#           # Prepare the JSON payload for the API request
#           PAYLOAD=$(echo '{}' | jq --arg name "$NEW_RUN_NAME" '.name = $name')

#           # Send the API request to rename the run name
#           curl -X PATCH -H "$AUTH_HEADER" -H "Accept: application/vnd.github.v3+json" -d "$PAYLOAD" "$API_URL"
#       - name: Checkout codebase
#         uses: actions/checkout@v3
        
#       - name: Upload
#         uses: actions/upload-artifact@v3.1.2
#         with:
#           name: asc_file
#           path: android/app/build/outputs/apk/release/app-release.apk

      - name: Generate sum 
        run: echo "### Branch used $GITHUB_REF_NAME" >> $GITHUB_STEP_SUMMARY
