name: Upload staging config to S3
run-name: Upload staging config to S3 ${{ github.run_number }}

on: 
  pull_request:
    branches:
      main

jobs:
  build:
    name: Dummy workflow dispatch
    runs-on: macos-latest

    steps:
      - name: Checkout codebase
        run: echo "Dummy workflow_dispatch - using feature branch"
        
