name: inputs.uploadToAWS
run-name: Upload staging config to S3 ${{ github.run_number }}

on: 
  workflow_dispatch:
    inputs:
      generateQA1:
        type: boolean
        default: false
        description: Generate QA1 build
      generatePROD:
        type: boolean
        default: false
        description: Generate PROD build
      uploadToAWS:
        type: boolean
        default: false
        description: Upload non-dev artifacts to S3

jobs:
  build:
    name: Dummy workflow dispatch
    runs-on: windows-latest

    steps:
      # - name: Checkout codebase
      #   uses: actions/checkout@v3

      
          

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: msbuild
      #     path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
        
     
        
      # - run: |
      #     ls C:/Program Files/Microsoft Visual Studio/2022/Enterprise
      #   shell: bash
      
      - name: Install Node JS v10.15.3
        uses: actions/setup-node@v3
        with:
          node-version: 10.15.3

      # - name: Setup Python (Win)
      #   run: |
      #     choco install python2
      #     npm config set python c:\Python27\python.exe

      - name: Add msbuild to PATH
        shell: powershell
        run: |
          npm install --global windows-build-tools@4.0.0
          npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe"

      - name: List tree
        run: |
          $path = "C:\Program Files (x86)\MSBuild\"
          TREE $path /F

      - name: List tree 2
        run: |
          $path = "C:\Program Files (x86)\Microsoft Visual Studio\"
          TREE $path /F
      
      - name: List files
        run: |
          $path = "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140"
          Get-ChildItem -Path $path

      - name: List files 2
        run: |
          $path = "C:\Program Files (x86)\MSBuild\15.0\.Net"
          Get-ChildItem -Path $path

      - name: List files 3
        run: |
          $path = "C:\Program Files (x86)\Microsoft Visual Studio\"
          Get-ChildItem -Path $path

      - name: List files 4
        run: |
          $path = "C:\Program Files (x86)\"
          Get-ChildItem -Path $path

      - name: run VCTargetsPath
        run: |
          echo $env:VCTargetsPath
          echo $env:Path
      
      - name: echo $env:APPDATA
        run: |
          echo $env:APPDATA
          ls $env:APPDATA

      - name: Test print
        if: inputs.uploadToAWS == true && (inputs.generateQA1 == true || inputs.generatePROD == true)
        run: echo "test if"

      - name: Print artifacts S3 URLs
        env:
          ARTIFACT_S3_URL: https://s3.us-jj.com
        shell: bash
        run: |
          while IFS= read -r file; do
            filename=$(basename "$file")
            echo "${{ env.ARTIFACT_S3_URL }}$filename"
          done < <(find . -type f \( -name "WD-*" ! -name "WD-*-dev1-*" \))
        
